### ISSUE TITLE
Verify occasions consistently populate in chronological order under an event

### ISSUE THREAD

**Issue by AmandaLBaker** [jakemoves/cohort-server#179]

**Comment by jakemoves** [comment]
(assuming you're not done prepping this one...)

**Comment by helloCaller** [comment]
This has been implemented, now they populate in order by date. @jakemoves it's a bit strange that the server object orders them differently every time it's called though, no?

**Comment by jakemoves** [comment]
I think it's non-deterministic unless I add a sorting step on a specific field (i.e. startDate)...

If you're noticing that this slows things down on the FE rendering, I can add a sort on the backend, but there's two reasons we might do it on the FE for now:

- it adds complexity to the API because usually the specifics of the sort can be specified in the query from the front end. Like, `GET /api/v2/events/4/occasions?sortBy=date`

- as you can see from the above sample, this pattern is usually used for granular calls, whereas we currently get occasions by calling for events and nesting occasions within (so it's not obvious how to implement the above pattern for such nested resources)

**Comment by AmandaLBaker** [comment]
Populating in the correct order
